[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.121.2"  # oppure una versione che vuoi usare
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"