backend:
  name: github
  repo: luigimassaroACN/decap-hugo-starter
  branch: main
  auth_type: pkce
  app_id: AUTH0_CLIENT_ID
  base_url: https://YOUR_TENANT.auth0.com
  login: true

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
